name: Update Lottery Data

on:
  schedule:
    - cron: '0 * * * *' # Gira ogni ora
  workflow_dispatch: # Ti permette di avviarlo a mano cliccando il tasto

permissions:
  contents: write # FONDAMENTALE: permette a GitHub di salvare il file JSON

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run script
        run: python update_jackpots.py
        python update_powerball.py

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add lottery_data.json
          git commit -m "Auto-update jackpots" || exit 0
          git push
